spring:
  jpa:
    hibernate:
      ddl-auto: update

  config:
    activate:
      on-profile: local
    import: application-secret.yml

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: / # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true