spring:
  jpa:
    hibernate:
      ddl-auto: update

  config:
    activate:
      on-profile: local
    import: application-secret.yml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true